# Generated by Django 5.0.14 on 2026-07-11 06:45

import apps.scans.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('successful_image_count', models.PositiveIntegerField(default=0)),
                ('failed_image_count', models.PositiveIntegerField(default=0)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.scans.models.get_temp_image_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scans.scansession')),
            ],
        ),
        migrations.CreateModel(
            name='ScanCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🍅', max_length=20)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('storage_zone', models.CharField(default='pantry', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('confidence', models.CharField(default='High', max_length=20)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='scans.scanimage')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='scans.scansession')),
            ],
        ),
    ]
