# Generated by Django 5.0.14 on 2026-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scancandidate',
            name='emoji',
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='icon_key',
            field=models.CharField(default='grocery', max_length=50),
        ),
    ]
