# Generated by Django 6.0.3 on 2026-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_remove_scancandidate_emoji_scancandidate_icon_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scancandidate',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='date_confidence',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='date_source',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='date_type',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='packed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='raw_date_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='shelf_life_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scancandidate',
            name='storage_reason',
            field=models.TextField(blank=True),
        ),
    ]
