# Generated by Django 5.0.14 on 2026-07-11 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('emoji', models.CharField(default='🍲', max_length=20)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('diet_type', models.CharField(default='veg', max_length=50)),
                ('prep_time_mins', models.PositiveIntegerField(default=30)),
                ('calories_per_serving', models.PositiveIntegerField(default=200)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('ingredients_used', models.JSONField(default=list)),
                ('other_ingredients', models.JSONField(default=list)),
                ('allergens', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('nutrition', models.JSONField(default=dict)),
                ('tip', models.TextField(blank=True)),
                ('allergen_warning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
