# Generated by Django 5.0.14 on 2026-07-11 06:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🌿', max_length=20)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('ml', 'ml'), ('pcs', 'pcs'), ('pack', 'pack'), ('bottle', 'bottle'), ('box', 'box'), ('dozen', 'dozen')], default='pcs', max_length=20)),
                ('storage_zone', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('counter', 'Counter'), ('cabinet', 'Cabinet'), ('basket', 'Basket'), ('spice', 'Spice')], default='pantry', max_length=20)),
                ('storage_notes', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='fresh', max_length=20)),
                ('calories_per_100g', models.PositiveIntegerField(blank=True, null=True)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('ai_detected', models.BooleanField(default=False)),
                ('ai_confidence', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('notified_3d', models.BooleanField(default=False)),
                ('notified_1d', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('item_added', 'Item Added'), ('scan_confirmed', 'Scan Confirmed'), ('quantity_increased', 'Quantity Increased'), ('quantity_decreased', 'Quantity Decreased'), ('quantity_corrected', 'Quantity Corrected'), ('consumed', 'Consumed'), ('wasted', 'Wasted'), ('item_updated', 'Item Updated'), ('item_deleted', 'Item Deleted')], max_length=50)),
                ('previous_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('new_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('grocery_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='groceries.groceryitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='groceryitem',
            index=models.Index(fields=['user', 'status'], name='groceries_g_user_id_19e988_idx'),
        ),
        migrations.AddIndex(
            model_name='groceryitem',
            index=models.Index(fields=['user', 'expiry_date'], name='groceries_g_user_id_f5bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='groceryitem',
            index=models.Index(fields=['user', 'storage_zone'], name='groceries_g_user_id_93bea2_idx'),
        ),
        migrations.AddIndex(
            model_name='groceryitem',
            index=models.Index(fields=['user', 'created_at'], name='groceries_g_user_id_95af5b_idx'),
        ),
    ]
