# Generated by Django 5.0.14 on 2026-07-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_remove_groceryitem_emoji_groceryitem_icon_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='confidence_score',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='freshness_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='predicted_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='recommended_consumption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='ripeness',
            field=models.CharField(choices=[('unripe', 'Unripe'), ('ripe', 'Ripe'), ('overripe', 'Overripe'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=30),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='storage_recommendation_how',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='storage_recommendation_shelf_life',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='storage_recommendation_why',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
