# Generated by Django 6.0.3 on 2026-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_groceryitem_ai_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='best_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='date_confidence',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='date_source',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='date_type',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='packed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='raw_date_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='shelf_life_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='storage_reason',
            field=models.TextField(blank=True),
        ),
    ]
