// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjSQ1LrVk7Ekc82jOeQUYKPJow1CHf2bA',
    appId: '1:956872126739:web:d4ea66b015f4ffb35b2ae6',
    messagingSenderId: '956872126739',
    projectId: 'grocerytracker-9ae8c',
    authDomain: 'grocerytracker-9ae8c.firebaseapp.com',
    storageBucket: 'grocerytracker-9ae8c.firebasestorage.app',
    measurementId: 'G-29Q17DRVF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvj3DGV9lPG1lZaQegF_vLTLJu8ej4rkw',
    appId: '1:956872126739:android:3ec4fab87c85aa555b2ae6',
    messagingSenderId: '956872126739',
    projectId: 'grocerytracker-9ae8c',
    storageBucket: 'grocerytracker-9ae8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUfIUx3ijV722_zU8WzONxS0VynyZP6GY',
    appId: '1:956872126739:ios:5392843fb92480315b2ae6',
    messagingSenderId: '956872126739',
    projectId: 'grocerytracker-9ae8c',
    storageBucket: 'grocerytracker-9ae8c.firebasestorage.app',
    iosBundleId: 'com.example.groceryTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUfIUx3ijV722_zU8WzONxS0VynyZP6GY',
    appId: '1:956872126739:ios:5392843fb92480315b2ae6',
    messagingSenderId: '956872126739',
    projectId: 'grocerytracker-9ae8c',
    storageBucket: 'grocerytracker-9ae8c.firebasestorage.app',
    iosBundleId: 'com.example.groceryTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjSQ1LrVk7Ekc82jOeQUYKPJow1CHf2bA',
    appId: '1:956872126739:web:03543b75817736af5b2ae6',
    messagingSenderId: '956872126739',
    projectId: 'grocerytracker-9ae8c',
    authDomain: 'grocerytracker-9ae8c.firebaseapp.com',
    storageBucket: 'grocerytracker-9ae8c.firebasestorage.app',
    measurementId: 'G-QGZWHEM7T0',
  );
}
