# Generated by Django 5.0.14 on 2026-07-11 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=30)),
                ('generation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('suggested_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('confidence', models.CharField(default='Medium', max_length=20)),
                ('source_signal', models.CharField(blank=True, max_length=100)),
                ('feedback', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('edited_then_accepted', 'Edited then Accepted'), ('rejected', 'Rejected'), ('ignored', 'Ignored')], default='pending', max_length=30)),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grocery_lists.grocerylist')),
            ],
        ),
    ]
